language: ruby
rvm:
- 2.2.5

install: gem install html-proofer
script: htmlproofer --check-html true .

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master       # test master branch ! this is a web repository !!

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
